apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: mahdiguettiti/test1:latest

        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  selector:
    app: ghost
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 31001
